a=int(input("Enter the first operand\n"))
b=int(input("Enter the second operand:\n"))
print("addition operation(+):",a+b)
print("subraction operation(-):",a-b)
print("multiplication operation(*):",a*b)
print("division operation(/):",int(a/b))
